// <auto-generated />
using System;
using System.Text.Json;
using BookLibrary.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookLibrary.Infrastructure.Migrations;

[DbContext(typeof(BookLibraryDbContext))]
[Migration("20260128000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("BookLibrary.Domain.Entities.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<JsonDocument>("ApiInfo")
                    .HasColumnType("jsonb")
                    .HasColumnName("api_info");

                b.Property<string>("Author")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("author");

                b.Property<string>("Isbn")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("isbn");

                b.Property<int>("PageCount")
                    .HasColumnType("integer")
                    .HasColumnName("pagecount");

                b.Property<int?>("PlaceId")
                    .HasColumnType("integer")
                    .HasColumnName("place_id");

                b.Property<string>("PublishedYear")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)")
                    .HasColumnName("published_year");

                b.Property<string>("Publisher")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("publisher");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("title");

                b.HasKey("Id");

                b.HasIndex("PlaceId");

                b.ToTable("books", (string)null);
            });

        modelBuilder.Entity("BookLibrary.Domain.Entities.Place", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Descr")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("descr");

                b.HasKey("Id");

                b.ToTable("places", (string)null);
            });

        modelBuilder.Entity("BookLibrary.Domain.Entities.Book", b =>
            {
                b.HasOne("BookLibrary.Domain.Entities.Place", "Place")
                    .WithMany("Books")
                    .HasForeignKey("PlaceId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Place");
            });

        modelBuilder.Entity("BookLibrary.Domain.Entities.Place", b =>
            {
                b.Navigation("Books");
            });
#pragma warning restore 612, 618
    }
}
